version: "3"
services:
  db:
    image: postgres:13
    #read_only: true
    container_name: postgres_typeorm_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dkdldhvp789"
    volumes:
      - ./data:/var/lib/postgresql/data
